---
title: "Baseball"
author: "Alan T. Arnholt"
date: 'Last compiled: `r format(Sys.time(), "%b %d, %Y")`'
output: 
  bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, message = FALSE, warning = FALSE, fig.align = "center")
```

Create the data set discussed on page 248 of Open Intro.

```{r, label = "BBsetup"}
library(dplyr)
library(openintro)
bat10 <- mlbBat10 %>%
  filter(AB > 200)
# Note unused factor levels
table(bat10$position)
bat10$position <- droplevels(bat10$position)
table(bat10$position)
# Combine 1B, 2B, 3B, SS into infield (IF)
#
bat10$pos <- plyr::revalue(bat10$position, 
                       replace = c("1B" = "IF", "2B" = "IF", "3B" = "IF", "SS" = "IF"))
table(bat10$pos)
# Note must detach plyr for dplyr to work properly
# detach("package:plyr", unload = TRUE)
```

Create summary statistics presented in Table 5.24 of Open Intro.

```{r}
T524 <- bat10 %>%
  group_by(pos) %>%
  summarise(n = n(), Mean = round(mean(OBP), 4), SD = round(sd(OBP), 4))
T524
```

```{r}
DT::datatable(T524)
```

```{r, label = "BPOI", fig.cap = "Side-by-side boxplots of on base percentage according to position"}
library(ggplot2)
ggplot(data = bat10, aes(x = pos, y = OBP, fill = pos)) + 
  geom_boxplot() + 
  theme_bw() + 
  labs(y = "On base percentage", x = "Position") + 
  guides(fill = FALSE)
```

```{r, label = "QQ", fig.width = 10}
ggplot(data = bat10, aes(sample = OBP, color = pos)) + 
  stat_qq() + 
  theme_bw()
ggplot(data = bat10, aes(sample = OBP, color = pos)) + 
  stat_qq() +
  facet_grid(.~pos) +
  theme_bw() + 
  guides(color = FALSE)
```

```{r}
mod.aov <- aov(OBP ~ pos, data = bat10)
summary(mod.aov)
```

**Finished - Now consider a different problem.**

```{r, fig.width = 10}
T5N <- bat10 %>%
  group_by(position) %>%
  summarise(n = n(), Mean = round(mean(OBP), 4), SD = round(sd(OBP), 4))
T5N
ggplot(data = bat10, aes(x = position, y = OBP, fill = position)) + 
  geom_boxplot() + 
  theme_bw() + 
  guides(fill = FALSE)
ggplot(data = bat10, aes(sample = OBP, color = position)) + 
  stat_qq() + 
  theme_bw()
ggplot(data = bat10, aes(sample = OBP, color = position)) + 
  stat_qq() +
  facet_grid(.~position) +
  theme_bw() + 
  guides(color = FALSE)
```

```{r}
mod2.aov <- aov(OBP ~ position, data = bat10)
summary(mod2.aov)
```

```{r, fig.width = 8, fig.height = 8}
TukeyHSD(mod2.aov)
par(las = 1)
plot(TukeyHSD(mod2.aov))
par(las = 0)
```

-----

## Confidence Intervals (2 Groups) {-}

```{r}
NDF <- bat10 %>%
  filter(team == "BAL" | team == "BOS") %>%
  select(OBP, team) 
NDF %>%
  group_by(team) %>%
  summarize(Mean = mean(OBP), SD = sd(OBP), n = n())
ggplot(data = NDF, aes(x = team, y = OBP)) + 
  geom_boxplot() + 
  theme_bw()
# Standard 90% CI first
t.test(OBP ~ team, data = NDF, conf.level = 0.90)
df <- t.test(OBP ~ team, data = NDF, conf.level = 0.90)$parameter
df
```

## Bootstrap {-}

```{r}
BALOBP <- bat10$OBP[bat10$team == "BAL"]
BOSOBP <- bat10$OBP[bat10$team == "BOS"]
obsdiff <- mean(BALOBP) - mean(BOSOBP)
obsdiff
SIMS <- 10^4 - 1
diffmean <- numeric(SIMS)
for(i in 1:SIMS){
  sampBAL <- sample(BALOBP, size = sum(!is.na(BALOBP)), replace = TRUE)
  sampBOS <- sample(BOSOBP, size = sum(!is.na(BOSOBP)), replace = TRUE)
  diffmean[i] <- mean(sampBAL) - mean(sampBOS)
}
hist(diffmean)
# OR
ggplot(data = data.frame(x = diffmean), aes(x = x)) + 
  geom_density(fill = "pink") + 
  theme_bw() + 
  labs(x = substitute(paste(bar(x)[Bal],"*", - bar(x)[Bos],"*")))
```

## Percentile Approach {-}

```{r}
BSCI <- quantile(diffmean, probs = c(0.05, 0.95))
BSCI
```

## Standard Bootstrap {-}

```{r}
SBS <- obsdiff + c(-1, 1)*qt(0.95, df)*sd(diffmean)
SBS
```

